# Generated by Django 5.2 on 2025-04-18 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('parse', 'Resume parsed'), ('analyze', 'Resume analyzed'), ('error', 'Error occurred'), ('upload', 'Resume uploaded'), ('register', 'User registered'), ('apply', 'Job application submitted'), ('create_job', 'Job created')], max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'analytics_logentry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
