# Generated by Django 5.2 on 2025-04-18 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='recruiters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'recruiter'}, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
